spring:
  application:
    name: posbackend
  datasource:
    url: jdbc:mysql://localhost:3306/librarymanagement-schema?useSSL=false
    username: root
    password: rootUser@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        formatSql: true
    database: mysql

#spring:
  # cache connection information
  redis:
    host: localhost
    port: 6379
    timeout: 10000 # in milliseconds

  # caching configuration
  cache:
    redis:
      cache-null-values: false
      # use the following two in conjunction
      use-key-prefix: true
      key-prefix: library
      time-to-live: 60000 # in milliseconds

server:
  port: 8001
